{% set version = "4.1.0" %}

package:
  name: roman-numerals-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/roman-numerals-py/roman_numerals_py-{{ version }}.tar.gz
  sha256: f5d7b2b4ca52dd855ef7ab8eb3590f428c0b1ea480736ce32b01fef2a5f8daf9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.7
  run:
    - roman-numerals ==4.1.0
    - python >={{ python_min }}

test:
  imports:
    - roman_numerals
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AA-Turner/roman-numerals
  license: 0BSD OR CC0-1.0
  license_file: LICENCE.rst
  summary: Manipulate well-formed Roman numerals
  dev_url: https://github.com/AA-Turner/roman-numerals

extra:
  recipe-maintainers:
    - AA-Turner
